# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test equality check in GitHub action as number
        if: ${{ matrix.python-version == 3.9 }}
        run: echo 'Running in Python 3.9 (works as number)'


      - name: Test equality check in GitHub action as string
        if: ${{ matrix.python-version == '3.9' }}
        run: echo 'Running in Python 3.9 (works as string)'
